/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;

/**
 *
 * @author hp
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        setSize(1600,900);
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hlb = new javax.swing.JLabel();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Home Page");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        hlb.setFont(new java.awt.Font("Agency FB", 1, 75)); // NOI18N
        hlb.setForeground(new java.awt.Color(255, 183, 25));
        hlb.setText("Admin Home");
        getContentPane().add(hlb);
        hlb.setBounds(620, 110, 330, 80);

        bt2.setBackground(new java.awt.Color(0, 0, 0));
        bt2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 183, 25));
        bt2.setText("View Bookings");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(800, 240, 350, 150);

        bt3.setBackground(new java.awt.Color(0, 0, 0));
        bt3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bt3.setForeground(new java.awt.Color(255, 183, 25));
        bt3.setText("Change Password");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(400, 470, 360, 150);

        bt1.setBackground(new java.awt.Color(0, 0, 0));
        bt1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 183, 25));
        bt1.setText("Manage Cars");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(400, 240, 360, 150);

        bt4.setBackground(new java.awt.Color(0, 0, 0));
        bt4.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bt4.setForeground(new java.awt.Color(255, 183, 25));
        bt4.setText("Logout");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt4);
        bt4.setBounds(800, 470, 350, 150);

        bt5.setBackground(new java.awt.Color(255, 183, 25));
        bt5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt5.setText("<-----");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        getContentPane().add(bt5);
        bt5.setBounds(20, 20, 73, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myuploads/adminhomeFINAL.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        AdminBookingHistory h = new AdminBookingHistory();
        h.setVisible(true);
        
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
            // TODO add your handling code here:
        AdminManageCars a = new AdminManageCars();
        a.setVisible(true);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        AdminChangePassword a = new AdminChangePassword();
        a.setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        int lo = JOptionPane.showConfirmDialog(this,"Are you sure you wanna log out?");
        if(lo==JOptionPane.YES_OPTION){
            global.uname = "";
            Welcome w = new Welcome();
            w.setVisible(true);
        }
        else {

        }


    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
       AdminLogin ob = new AdminLogin();
        ob.setVisible(true);

    }//GEN-LAST:event_bt5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JLabel hlb;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
