/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import vmm.DBLoader;

import javax.swing.*;
import java.sql.ResultSet;

/**
 *
 * @author hp
 */
public class AdminChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form AdminChangePassword
     */
    public AdminChangePassword() {
        initComponents();
        setSize(1600,900);
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pf2 = new javax.swing.JPasswordField();
        pf3 = new javax.swing.JPasswordField();
        pf1 = new javax.swing.JPasswordField();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdminChangePassword");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 167, 0));
        jLabel1.setText("Reset Admin Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 110, 730, 80);

        bt1.setBackground(new java.awt.Color(0, 0, 0));
        bt1.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        bt1.setForeground(new java.awt.Color(223, 167, 0));
        bt1.setText("Change Password");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(520, 520, 620, 100);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(223, 167, 0));
        jLabel2.setText("OLD PASSWORD : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 260, 210, 40);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 167, 0));
        jLabel3.setText("NEW PASSWORD : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 340, 210, 36);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(223, 167, 0));
        jLabel4.setText("CONFIRM NEW PASSWORD : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 420, 270, 36);

        pf2.setBackground(new java.awt.Color(0, 0, 0));
        pf2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        pf2.setForeground(new java.awt.Color(223, 167, 0));
        pf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf2ActionPerformed(evt);
            }
        });
        getContentPane().add(pf2);
        pf2.setBounds(800, 330, 340, 50);

        pf3.setBackground(new java.awt.Color(0, 0, 0));
        pf3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        pf3.setForeground(new java.awt.Color(223, 167, 0));
        pf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf3ActionPerformed(evt);
            }
        });
        getContentPane().add(pf3);
        pf3.setBounds(800, 410, 340, 50);

        pf1.setBackground(new java.awt.Color(0, 0, 0));
        pf1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        pf1.setForeground(new java.awt.Color(223, 167, 0));
        pf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf1ActionPerformed(evt);
            }
        });
        getContentPane().add(pf1);
        pf1.setBounds(800, 250, 340, 50);

        bt2.setBackground(new java.awt.Color(225, 179, 40));
        bt2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt2.setText("<-----");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(20, 20, 73, 25);

        bt3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt3.setText("<-----");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(20, 20, 73, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myuploads/adminchangepassword.jpg"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(1534, 775));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1540, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf2ActionPerformed

    private void pf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf3ActionPerformed

    private void pf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf1ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        try {
            String email = global.uname;
            ResultSet rs = DBLoader.executeQuery("select * from admin where email = '"+email+"' ");
            String op = pf1.getText();
            String np = pf2.getText();
            String cp = pf3.getText();


            rs.next();
                String oldpass = rs.getString("password");

                if (np.equals(cp)) {
                    if ((np.equals(op))) {
                        JOptionPane.showMessageDialog(this, "old password and new password is same!");
                    }
                    else {
                        if (op.equals(oldpass)) {
                            rs.updateString("password", np);
                            rs.updateRow();
                            JOptionPane.showMessageDialog(this, "password changed!");
                        }
                        else {
                            JOptionPane.showMessageDialog(this, "error");
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "new and confirmed passwords are different!");
                }
                pf1.setText("");
                pf2.setText("");
                pf3.setText("");


        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        AdminHome ob = new AdminHome();
        ob.setVisible(true);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        AdminHome ob = new AdminHome();
        ob.setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JPasswordField pf2;
    private javax.swing.JPasswordField pf3;
    // End of variables declaration//GEN-END:variables
}
