/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import vmm.DBLoader;

import javax.swing.*;
import java.sql.*;

/**
 *
 * @author hp
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        setSize(1600,900);
        setExtendedState(MAXIMIZED_BOTH);   
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        elbl = new javax.swing.JLabel();
        pslbl = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        pf1 = new javax.swing.JPasswordField();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        elbl1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Login");
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(null);

        elbl.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        elbl.setForeground(new java.awt.Color(223, 167, 0));
        elbl.setText("Username:");
        getContentPane().add(elbl);
        elbl.setBounds(530, 270, 110, 30);

        pslbl.setBackground(new java.awt.Color(0, 0, 0));
        pslbl.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        pslbl.setForeground(new java.awt.Color(223, 167, 0));
        pslbl.setText("Password : ");
        getContentPane().add(pslbl);
        pslbl.setBounds(530, 340, 130, 40);

        tf1.setBackground(new java.awt.Color(0, 0, 0));
        tf1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf1.setForeground(new java.awt.Color(225, 179, 40));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(650, 260, 340, 50);

        pf1.setBackground(new java.awt.Color(0, 0, 0));
        pf1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        pf1.setForeground(new java.awt.Color(225, 179, 40));
        pf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf1ActionPerformed(evt);
            }
        });
        getContentPane().add(pf1);
        pf1.setBounds(650, 340, 340, 50);

        bt1.setBackground(new java.awt.Color(0, 0, 0));
        bt1.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        bt1.setForeground(new java.awt.Color(223, 167, 0));
        bt1.setText("Login");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(530, 450, 460, 110);

        bt2.setBackground(new java.awt.Color(225, 179, 40));
        bt2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt2.setText("<-----");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(20, 20, 73, 25);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 167, 0));
        jLabel1.setText("Admin Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 150, 330, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myuploads/adminlogin2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1600, 900);

        elbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        elbl1.setForeground(new java.awt.Color(225, 179, 40));
        elbl1.setText("Email : ");
        getContentPane().add(elbl1);
        elbl1.setBounds(590, 230, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        try{
            String em  = tf1.getText();
            String ps = pf1.getText();
            ResultSet rs = DBLoader.executeQuery("select * from admin where email = '"+em+"' and password = '"+ps+"' ");
            if(rs.next())
            {
//                JOptionPane.showMessageDialog(this, "Login Successfull");
                AdminHome ob1 = new AdminHome();
                global.uname=em;
                ob1.setVisible(true);
                dispose();

            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid Email or Password");
            }
        } catch (Exception e) {
            e.getStackTrace();
        }

    }//GEN-LAST:event_bt1ActionPerformed

    private void pf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf1ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        Welcome ob = new Welcome();
        ob.setVisible(true);
        
    }//GEN-LAST:event_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JLabel elbl;
    private javax.swing.JLabel elbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JLabel pslbl;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables

    
}
