/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import vmm.DBLoader;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author hp
 */
public class AdminAddCars extends javax.swing.JFrame {

    String path;

    /**
     * Creates new form AdminAddCars
     */
    public AdminAddCars() {
        initComponents();
        setSize(1600,900);

        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        cb2 = new javax.swing.JComboBox<>();
        cb3 = new javax.swing.JComboBox<>();
        cb1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bt3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AddAnewCar");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 167, 0));
        jLabel1.setText("Add A New Car");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 30, 390, 70);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(223, 167, 0));
        jLabel2.setText("Car Name : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 140, 91, 29);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 167, 0));
        jLabel3.setText("Brand : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 220, 71, 40);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(223, 167, 0));
        jLabel4.setText("Car Type : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 260, 90, 40);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(223, 167, 0));
        jLabel5.setText("Fuel Type : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 300, 97, 40);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(223, 167, 0));
        jLabel6.setText("Price per day (without driver) : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 350, 250, 40);

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(223, 167, 0));
        jLabel7.setText("Price per day (with driver) : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 390, 237, 40);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(223, 167, 0));
        jLabel8.setText("Security : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 430, 80, 40);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(223, 167, 0));
        jLabel10.setText("Photo : ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 590, 92, 29);

        tf1.setBackground(new java.awt.Color(0, 0, 0));
        tf1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf1.setForeground(new java.awt.Color(223, 167, 0));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(740, 140, 340, 40);

        tf3.setBackground(new java.awt.Color(0, 0, 0));
        tf3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf3.setForeground(new java.awt.Color(223, 167, 0));
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(740, 350, 340, 40);

        tf5.setBackground(new java.awt.Color(0, 0, 0));
        tf5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf5.setForeground(new java.awt.Color(223, 167, 0));
        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        getContentPane().add(tf5);
        tf5.setBounds(740, 430, 340, 40);

        tf4.setBackground(new java.awt.Color(0, 0, 0));
        tf4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf4.setForeground(new java.awt.Color(223, 167, 0));
        getContentPane().add(tf4);
        tf4.setBounds(740, 390, 340, 40);

        cb2.setBackground(new java.awt.Color(0, 0, 0));
        cb2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        cb2.setForeground(new java.awt.Color(223, 167, 0));
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Hatchback", "Sedan", "SUV", "MSUV", "Hatchback(Luxury)", "Sedan(Luxury)", "SUV(Luxury)", "MSUV(Luxury)" }));
        getContentPane().add(cb2);
        cb2.setBounds(740, 260, 340, 40);

        cb3.setBackground(new java.awt.Color(0, 0, 0));
        cb3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        cb3.setForeground(new java.awt.Color(223, 167, 0));
        cb3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Petrol", "Diesel", "Hybrid" }));
        getContentPane().add(cb3);
        cb3.setBounds(740, 300, 340, 40);

        cb1.setBackground(new java.awt.Color(0, 0, 0));
        cb1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        cb1.setForeground(new java.awt.Color(223, 167, 0));
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Toyota", "Ford", "Mahindra", "Datsun", "Nissan", "Hyundai", "Tata", "Kia", "Skoda", "Honda", "Lamborghini", "Mercedes", "BMW", "Lexus", "Volvo" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(740, 220, 340, 40);

        ta1.setBackground(new java.awt.Color(0, 0, 0));
        ta1.setColumns(20);
        ta1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        ta1.setForeground(new java.awt.Color(223, 167, 0));
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(740, 480, 340, 110);

        bt1.setBackground(new java.awt.Color(0, 0, 0));
        bt1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(223, 167, 0));
        bt1.setText("Choose Photo");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(950, 670, 130, 40);

        bt2.setBackground(new java.awt.Color(0, 0, 0));
        bt2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        bt2.setForeground(new java.awt.Color(223, 167, 0));
        bt2.setText("Add");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(740, 720, 350, 50);
        getContentPane().add(lb1);
        lb1.setBounds(740, 590, 200, 130);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(223, 167, 0));
        jLabel12.setText("Number plate : ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(460, 180, 270, 40);

        tf2.setBackground(new java.awt.Color(0, 0, 0));
        tf2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf2.setForeground(new java.awt.Color(223, 167, 0));
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(740, 180, 340, 40);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(223, 167, 0));
        jLabel11.setText("Description : ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 480, 120, 29);

        bt3.setBackground(new java.awt.Color(225, 179, 40));
        bt3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 0, 0));
        bt3.setText("<-----");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(20, 20, 73, 25);

        jLabel13.setForeground(new java.awt.Color(223, 167, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myuploads/welcomepagenew2.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1600, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf5ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int a = chooser.showOpenDialog(this);
        if (a == JFileChooser.APPROVE_OPTION) {
            File f1 = chooser.getSelectedFile();
            String path = f1.getPath();
            int start = path.indexOf("src");
            this.path = path.substring(start);
            System.out.println(this.path);
            lb1.setIcon(new ImageIcon(new ImageIcon(this.path).getImage().getScaledInstance(lb1.getWidth(), lb1.getHeight(), Image.SCALE_SMOOTH)));

        }


    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        try {
            if(tf1.getText().trim().equals("") || tf2.getText().trim().equals("") || tf3.getText().trim().equals("") ||  tf4.getText().trim().equals("") || tf5.getText().trim().equals("") || cb1.getSelectedIndex()==0 || cb2.getSelectedIndex()==0 || cb3.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(null, "Please fill all the fields");
            }
            else{

                ResultSet rs = DBLoader.executeQuery("select * from car_details");

                rs.moveToInsertRow();
                rs.updateString("car_names", tf1.getText());
                rs.updateString("no_plate", tf2.getText());
                rs.updateString("brand", cb1.getSelectedItem().toString());
                rs.updateString("car_type", cb2.getSelectedItem().toString());
                rs.updateString("fuel_type", cb3.getSelectedItem().toString());
                rs.updateString("perday_price_with_driver", tf4.getText());
                rs.updateString("perday_price_without_driver", tf3.getText());
                rs.updateString("security", tf5.getText());
                rs.updateString("description", ta1.getText());
                rs.updateString("photo", this.path);
                rs.insertRow();
                tf1.setText("");
                tf2.setText("");
                tf3.setText("");
                tf4.setText("");
                tf5.setText("");
                ta1.setText("");
                cb1.setSelectedItem(null);
                cb2.setSelectedItem(null);
                cb3.setSelectedItem(null);
                JOptionPane.showMessageDialog(null, "Car Added Successfully!!");
                AdminManageCars admin = new AdminManageCars();
                admin.setVisible(true);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_bt2ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        AdminManageCars ob = new AdminManageCars();
        ob.setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JComboBox<String> cb3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
