/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import vmm.DBLoader;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;

/**
 *
 * @author hp
 */
public class AdminManageCars extends javax.swing.JFrame {

    /**
     * Creates new form AdminManageCars
     */
    ArrayList<car_details> al = new ArrayList<>();
    mytablemodel tm;

    public AdminManageCars() {

        initComponents();
        setSize(1600,900);
        try {
            ResultSet rs = DBLoader.executeQuery("select * from car_details");
            while (rs.next()) {
                int Car_id = rs.getInt("Car_id");
                String Car_Names = rs.getString("Car_Names");
                String No_plate = rs.getString("No_plate");
                String Brand = rs.getString("Brand");
                String Car_Type = rs.getString("Car_Type");
                String Fuel_Type = rs.getString("Fuel_Type");
                String perday_price_without_driver = rs.getString("perday_price_without_driver");
                String perday_price_with_driver = rs.getString("perday_price_with_driver");
                String Security = rs.getString("Security");
                String description = rs.getString("description");
                String Photo = rs.getString("Photo");
                al.add(new car_details(Car_id, Car_Names, No_plate, Brand, Car_Type, Fuel_Type, perday_price_without_driver, perday_price_with_driver, Security, description, Photo));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        tm = new mytablemodel();
        jt1.setModel(tm);
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Manage Cars");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(java.awt.Color.black);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(225, 179, 40));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 167, 0));
        jLabel1.setText("Already Added Cars");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 30, 520, 90);

        bt1.setBackground(new java.awt.Color(0, 0, 0));
        bt1.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        bt1.setForeground(new java.awt.Color(223, 167, 0));
        bt1.setText("Add a new car");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(480, 620, 290, 100);

        bt2.setBackground(new java.awt.Color(0, 0, 0));
        bt2.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        bt2.setForeground(new java.awt.Color(223, 167, 0));
        bt2.setText("Remove car");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(830, 620, 300, 100);

        bt3.setBackground(new java.awt.Color(223, 167, 0));
        bt3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt3.setText("<-----");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(20, 20, 73, 25);

        jt1.setAutoCreateRowSorter(true);
        jt1.setBackground(new java.awt.Color(0, 0, 0));
        jt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 179, 40)));
        jt1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jt1.setForeground(new java.awt.Color(223, 167, 0));
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car_id", "Car_Names", "No_plate", "Brand", "Car_Type", "Fuel_Type", "perday_price_without_driver", "perday_price_with_driver", "Security", "description", "Photo"
            }
        ));
        jt1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jt1.setGridColor(new java.awt.Color(223, 167, 0));
        jt1.setMaximumSize(new java.awt.Dimension(2147483647, 160));
        jt1.setMinimumSize(new java.awt.Dimension(60, 160));
        jt1.setPreferredSize(new java.awt.Dimension(300, 700));
        jt1.setRowHeight(40);
        jt1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jt1.setShowGrid(true);
        jScrollPane1.setViewportView(jt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 150, 1420, 440);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myuploads/adminmanagecars.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1540, 870);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int del = jt1.getSelectedRow();
        try {
            int lo = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this car?");
            if (lo == JOptionPane.YES_OPTION) {

                ResultSet rs = DBLoader.executeQuery("select * from car_details ");
                rs.absolute(del + 1);
                rs.deleteRow();
                al.remove(del);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        tm.fireTableDataChanged();
    }


    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        AdminAddCars a = new AdminAddCars();
        a.setVisible(true);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        AdminHome ob = new AdminHome();
        ob.setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    class mytablemodel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return 11;
        }

        @Override
        public Object getValueAt(int i, int j) {
            car_details c = (car_details) al.get(i);
            if (j == 0) {
                return c.Car_id;
            } else if (j == 1) {
                return c.Car_Names;
            } else if (j == 2) {
                return c.No_plate;
            } else if (j == 3) {
                return c.Brand;
            } else if (j == 4) {
                return c.Car_Type;
            } else if (j == 5) {
                return c.Fuel_Type;
            } else if (j == 6) {
                return c.perday_price_with_driver;
            } else if (j == 7) {
                return c.perday_price_without_driver;
            } else if (j == 8) {
                return c.Security;
            } else if (j == 9) {
                return c.description;
            } else {
                return c.Photo;
            }
        }

        public String getColumnName(int column) {
            String name[] = {"Car_id", "Car_Names", "No_plate", "Brand", "Car_Type", "Fuel_Type", "perday_price_without_driver", "perday_price_with_driver", "Security", "description", "Photo"};
            return name[column];
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManageCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManageCars().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt1;
    // End of variables declaration//GEN-END:variables
}
