/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import vmm.DBLoader;

import javax.swing.*;
import java.awt.*;

import java.sql.ResultSet;
import java.text.DateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;

/**
 *
 * @author hp
 */
public class Booking extends javax.swing.JFrame {

    String carid;
    String rentwith;
    String rentwithout;
    String from;
    String to;

    /**
     * Creates new form Booking
     */
    public Booking(String carid) {
        this.carid = carid;
        initComponents();
        setSize(1600,900);
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);

        try {

            ResultSet rs = DBLoader.executeQuery("select * from car_details where Car_id='" + carid + "'");
            rs.next();
            String name = rs.getString("Car_Names");
            String brand = rs.getString("Brand");
            String security = rs.getString("Security");
            String fuel = rs.getString("Fuel_Type");
            String photo = rs.getString("Photo");
            this.rentwith = rs.getString("perday_price_with_driver");
            this.rentwithout = rs.getString("perday_price_without_driver");

            lb1.setIcon(new ImageIcon(new ImageIcon(photo).getImage().getScaledInstance(lb1.getWidth(), lb1.getHeight(), Image.SCALE_DEFAULT)));

            lb2.setText("Name of the car : " + name);
            lb3.setText("Brand : " + brand);
            lb4.setText("Security : " + security);
            lb5.setText("Fuel type : " + fuel);
            lbPWD.setText("(Rs." + rentwith + ")");
            lbPWoutD.setText(" (Rs." + rentwithout + ")");

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lb1 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        dc2 = new com.toedter.calendar.JDateChooser();
        bt1 = new javax.swing.JButton();
        lb4 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        dc1 = new com.toedter.calendar.JDateChooser();
        bt3 = new javax.swing.JButton();
        lbPWD = new javax.swing.JLabel();
        lbPWoutD = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserBookingBeforePayment");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 183, 25));
        lb1.setPreferredSize(new java.awt.Dimension(400, 250));
        getContentPane().add(lb1);
        lb1.setBounds(420, 100, 400, 250);

        lb3.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb3);
        lb3.setBounds(870, 160, 340, 50);

        lb5.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb5);
        lb5.setBounds(870, 310, 340, 50);

        lb2.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb2);
        lb2.setBounds(870, 90, 340, 50);

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        rb2.setForeground(new java.awt.Color(255, 183, 25));
        rb2.setText("Without driver  ");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(880, 560, 220, 40);

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        rb1.setForeground(new java.awt.Color(255, 183, 25));
        rb1.setText("With driver");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(880, 620, 160, 40);

        dc2.setBackground(new java.awt.Color(0, 0, 0));
        dc2.setToolTipText("");
        dc2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        dc2.setIcon(null);
        dc2.setInheritsPopupMenu(true);
        getContentPane().add(dc2);
        dc2.setBounds(880, 490, 210, 40);

        bt1.setBackground(new java.awt.Color(0, 0, 0));
        bt1.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        bt1.setForeground(new java.awt.Color(223, 167, 0));
        bt1.setText("BOOK");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(580, 680, 450, 90);

        lb4.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb4);
        lb4.setBounds(870, 240, 340, 50);

        lb6.setBackground(new java.awt.Color(5, 0, 0));
        lb6.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lb6.setForeground(new java.awt.Color(255, 183, 25));
        lb6.setText("Per day rent : ");
        getContentPane().add(lb6);
        lb6.setBounds(540, 560, 170, 40);

        lb9.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lb9.setForeground(new java.awt.Color(255, 183, 25));
        lb9.setText("To : ");
        getContentPane().add(lb9);
        lb9.setBounds(540, 480, 90, 40);

        lb8.setFont(new java.awt.Font("Agency FB", 1, 35)); // NOI18N
        lb8.setForeground(new java.awt.Color(255, 183, 25));
        lb8.setText("From : ");
        getContentPane().add(lb8);
        lb8.setBounds(540, 420, 90, 40);

        dc1.setBackground(new java.awt.Color(0, 0, 0));
        dc1.setToolTipText("");
        dc1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        dc1.setIcon(null);
        dc1.setInheritsPopupMenu(true);
        getContentPane().add(dc1);
        dc1.setBounds(880, 420, 210, 40);

        bt3.setBackground(new java.awt.Color(255, 183, 25));
        bt3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt3.setText("<-----");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(20, 20, 73, 25);

        lbPWD.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        lbPWD.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lbPWD);
        lbPWD.setBounds(1040, 620, 110, 40);

        lbPWoutD.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        lbPWoutD.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lbPWoutD);
        lbPWoutD.setBounds(1070, 560, 120, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myuploads/booking1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1600, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:

        if (dc1.getDate() != null && dc2.getDate() != null) {
            System.out.println("brrrrrr");
            if (dc1.getCalendar().before(dc2.getCalendar())) {

                if (rb1.isSelected() || rb2.isSelected()) {
                    Date date = dc1.getDate();
                    Date date2 = dc2.getDate();
                    String from = date.toString();
                    String to = date2.toString();
                    Instant instant = date.toInstant();
                    Instant in = date2.toInstant();
                    LocalDate fromdate = instant.atZone(ZoneId.systemDefault()).toLocalDate();
                    LocalDate todate = in.atZone(ZoneId.systemDefault()).toLocalDate();
                    Period fp = Period.between(fromdate, todate);
                    String s = fp.toString();
                    int days = Integer.parseInt(s.substring(1, s.length() - 1));

                    if (rb1.isSelected()) {
                        Submission sub = new Submission(carid, rentwith, from, to, days);
                        sub.setVisible(true);
                    } else if (rb2.isSelected()) {
                        Submission sub = new Submission(carid, rentwithout, from, to, days);
                        sub.setVisible(true);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Select 'with/without driver' option!");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, " 'From' date cant be smaller than 'To'  date!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please fill all the information!");
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        UserHome ob = new UserHome();
        ob.setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt3;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dc1;
    private com.toedter.calendar.JDateChooser dc2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JLabel lbPWD;
    private javax.swing.JLabel lbPWoutD;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    // End of variables declaration//GEN-END:variables
}
