/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hp
 */
public class CarDesign extends javax.swing.JPanel {

    /**
     * Creates new form CarDesign
     */
    public CarDesign() {
        initComponents();
        setSize(1920, 1080  );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(25, 25, 25));
        setLayout(null);

        lb1.setPreferredSize(new java.awt.Dimension(350, 350));
        add(lb1);
        lb1.setBounds(20, 20, 400, 250);

        lb3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 183, 25));
        add(lb3);
        lb3.setBounds(500, 90, 1050, 40);

        lb4.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 183, 25));
        add(lb4);
        lb4.setBounds(500, 160, 1050, 40);

        lb5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 183, 25));
        add(lb5);
        lb5.setBounds(500, 230, 1050, 40);

        lb2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 183, 25));
        add(lb2);
        lb2.setBounds(500, 20, 1050, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lb1;
    public javax.swing.JLabel lb2;
    public javax.swing.JLabel lb3;
    public javax.swing.JLabel lb4;
    public javax.swing.JLabel lb5;
    // End of variables declaration//GEN-END:variables
}
