/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.mysql.cj.protocol.Resultset;
import vmm.DBLoader;

import javax.swing.table.AbstractTableModel;
import javax.swing.table.JTableHeader;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author hp
 */
public class SQLtoJTABLE extends javax.swing.JFrame {
    ArrayList<car_details> al = new ArrayList<>();
    mytablemodel tm;

    /**
     * Creates new form SQLtoJTABLE
     */
    public SQLtoJTABLE() {
        try{
            ResultSet rs = DBLoader.executeQuery("select * from car_details");
            while(rs.next())
            {
                int Car_id = rs.getInt("Car_id") ;
                String Car_Names  = rs.getString("Car_Names");
                String No_plate  = rs.getString("No_plate");
                String Brand  = rs.getString("Brand");
                String Car_Type  = rs.getString("Car_Type");
                String Fuel_Type  = rs.getString("Fuel_Type");
                String perday_price_without_driver  = rs.getString("perday_price_without_driver");
                String perday_price_with_driver  = rs.getString("perday_price_with_driver");
                String Security  = rs.getString("Security");
                String description  = rs.getString("description");
                String Photo  = rs.getString("Photo");

                al.add(new car_details(Car_id, Car_Names,No_plate,Brand, Car_Type, Fuel_Type, perday_price_without_driver, perday_price_with_driver, Security, description, Photo));

            }
        } catch(Exception ex)
        {
            ex.printStackTrace();
        }

        initComponents();
        tm = new mytablemodel();
        jt1.setModel(tm);


        setSize(1042, 598);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(14, 39, 1420, 403);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    class mytablemodel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return 11;
        }

        @Override
        public Object getValueAt(int i, int j) {
            car_details c = (car_details) al.get(i);
            if(j==0)
            {
                return c.Car_id;
            }
            else if(j==1)
                {
                return c.Car_Names;
                }
            else if(j==2)
                {
                    return c.No_plate;
                }
            else if(j==3)
                {
                    return c.Brand;
                }
            else if(j==4)
                {
                    return c.Car_Type;
                }
            else if(j==5)
                {
                    return c.Fuel_Type;
                }
            else if(j==6)
            {
                return c.perday_price_without_driver;
            }
            else if(j==7)
            {
                return c.perday_price_with_driver;
            }
            else if(j==8)
            {
                return c.Security;
            }
            else if(j==9)
            {
                return c.description;
            }
            else
            {
                return c.Photo;
            }
        }

        public String getColumnName(int column) {
            String name[] = {"Car_id", "Car_Names", "No_plate", "Brand", "Car_Type", "Fuel_Type", "perday_price_without_driver", "perday_price_with_driver", "Security", "description", "Photo"};
            return name[column];
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SQLtoJTABLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SQLtoJTABLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SQLtoJTABLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SQLtoJTABLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SQLtoJTABLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt1;
    // End of variables declaration//GEN-END:variables
}
