/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import vmm.DBLoader;

import javax.swing.*;
import java.sql.ResultSet;
import java.util.Date;

/**
 *
 * @author hp
 */
public class Submission extends javax.swing.JFrame {

    String total_rent = "";


    public Submission(String carid, String rentperday, String from, String to, int days) {

        initComponents();
        setSize(1600,900);
        try {
            ResultSet rs = DBLoader.executeQuery("Select * from car_details where Car_id='" + carid + "'");
            if (rs.next()) {
                String security = rs.getString("security");
                int rent = Integer.parseInt(rentperday) * days;
                int sec = Integer.parseInt(security);
                String total_rent = (rent + sec) + "";

                this.total_rent = total_rent;
                lb1.setText(carid);
                lb2.setText(rentperday);
                lb3.setText(from);
                lb4.setText(to);

                if (days == 0) {
                    days = 1;
                    rent = Integer.parseInt(rentperday) * days;
                    lb5.setText(days+"");
                    lb6.setText(rent + "");
                    total_rent = (rent + sec) + "";
                    this.total_rent = total_rent;


                } else {
                    lb5.setText(days + "");
                    lb6.setText(rent + "");
                }

                lb8.setText(security);
                lb7.setText(total_rent);

            } else {
                System.out.println("error");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        setSize(1492, 759);
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();
        bt2 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SubmissionPage");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jlabel1.setFont(new java.awt.Font("Agency FB", 1, 75)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 183, 25));
        jlabel1.setText("Booking Submission");
        getContentPane().add(jlabel1);
        jlabel1.setBounds(530, 20, 530, 90);

        jLabel2.setBackground(new java.awt.Color(5, 0, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 183, 25));
        jLabel2.setText("Price Per Day : ");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 180, 140, 30);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 183, 25));
        jLabel3.setText("Start Date : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 220, 110, 30);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 183, 25));
        jLabel4.setText("End Date :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 260, 110, 30);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 183, 25));
        jLabel5.setText("No. of Days : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 300, 120, 30);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 183, 25));
        jLabel6.setText("Rent : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 340, 110, 30);

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 183, 25));
        jLabel8.setText("Name : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 460, 110, 30);

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 183, 25));
        jLabel9.setText("Phone Number : ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(530, 500, 160, 30);

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 183, 25));
        jLabel11.setText("Car ID :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(530, 140, 110, 30);

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 183, 25));
        jLabel14.setText("Address : ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(530, 540, 110, 30);

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 183, 25));
        jLabel10.setText("Email : ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(530, 580, 110, 30);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 183, 25));
        jLabel12.setText("Payment : ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(530, 620, 110, 30);

        lb2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 183, 25));
        lb2.setText(" ");
        getContentPane().add(lb2);
        lb2.setBounds(830, 180, 230, 30);

        lb3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb3);
        lb3.setBounds(830, 220, 230, 30);

        lb4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 183, 25));
        lb4.setText(" ");
        getContentPane().add(lb4);
        lb4.setBounds(830, 260, 230, 30);

        lb5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lb5.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb5);
        lb5.setBounds(830, 300, 230, 30);

        lb6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lb6.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb6);
        lb6.setBounds(830, 340, 230, 30);

        lb7.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lb7.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb7);
        lb7.setBounds(830, 420, 230, 30);

        lb1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb1);
        lb1.setBounds(830, 140, 230, 30);

        tf2.setBackground(new java.awt.Color(0, 0, 0));
        tf2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf2.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(tf2);
        tf2.setBounds(830, 500, 230, 40);

        tf3.setBackground(new java.awt.Color(0, 0, 0));
        tf3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf3.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(tf3);
        tf3.setBounds(830, 540, 230, 40);

        tf4.setBackground(new java.awt.Color(0, 0, 0));
        tf4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf4.setForeground(new java.awt.Color(255, 183, 25));
        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        getContentPane().add(tf4);
        tf4.setBounds(830, 580, 230, 40);

        tf1.setBackground(new java.awt.Color(0, 0, 0));
        tf1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        tf1.setForeground(new java.awt.Color(255, 183, 25));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(830, 460, 230, 40);

        bt2.setBackground(new java.awt.Color(0, 0, 0));
        bt2.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 183, 25));
        bt2.setText("Sumbit");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(610, 670, 390, 80);

        bt1.setBackground(new java.awt.Color(255, 183, 25));
        bt1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt1.setText("Proceed");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(830, 620, 230, 30);

        bt3.setBackground(new java.awt.Color(255, 183, 25));
        bt3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 0, 0));
        bt3.setText("<-----");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(20, 20, 73, 25);

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 183, 25));
        jLabel13.setText("Security : ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(530, 380, 110, 30);

        lb8.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lb8.setForeground(new java.awt.Color(255, 183, 25));
        getContentPane().add(lb8);
        lb8.setBounds(830, 380, 230, 30);

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 183, 25));
        jLabel15.setText("Total amount : ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(530, 420, 140, 30);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 183, 25));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myuploads/submission 3.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1600, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = DBLoader.executeQuery("select * from booking");
            if (tf4.getText().equals(global.uname)) {

                rs.moveToInsertRow();
                rs.updateString("car_id", lb1.getText());
                rs.updateString("price_per_day", lb2.getText());
                rs.updateString("start_date", lb3.getText());
                rs.updateString("end_date", lb4.getText());
                rs.updateString("no_of_days", lb5.getText());
                rs.updateString("rent", lb6.getText());
                rs.updateString("security", lb8.getText());
                rs.updateString("name", tf1.getText());
                rs.updateString("mobile_no", tf2.getText());
                rs.updateString("address", tf3.getText());
                rs.updateString("email", tf4.getText());
                rs.updateString("payment_status", global.payment_status);
                rs.updateString("booking_status", "success");
                rs.insertRow();
                tf1.setText("");
                tf2.setText("");
                tf3.setText("");
                tf4.setText("");
                JOptionPane.showMessageDialog(null, "Booking Successful");
                UserBookingHistory bookingHistory = new UserBookingHistory();
                bookingHistory.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Invalid email!");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        vmm1 obj = new vmm1(total_rent);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        Booking ob = new Booking("");
        ob.setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submission("", "", "", "", 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
