/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import vmm.DBLoader;

import javax.swing.table.AbstractTableModel;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class UserBookingHistory extends javax.swing.JFrame {

    ArrayList<UserBookingData> al = new ArrayList<>();
    mytablemodel tm;

    public UserBookingHistory() {
        try {
            al.clear();
            ResultSet rs = DBLoader.executeQuery("select * from booking where email = '"+global.uname+"'");
            while (rs.next()) {
                int booking_id = rs.getInt("booking_id");
                int car_id = rs.getInt("Car_id");
                String price_per_day = rs.getString("price_per_day");
                String start_date = rs.getString("start_date");
                String end_date = rs.getString("end_date");
                String no_of_days = rs.getString("no_of_days");
                String rent = rs.getString("rent");
                String security = rs.getString("security");
                String name = rs.getString("name");
                String mobile_no = rs.getString("mobile_no");
                String address = rs.getString("address");
                String email = rs.getString("email");
                String payment_status = rs.getString("payment_status");
                String booking_status = rs.getString("booking_status");
                al.add(new UserBookingData(booking_id, car_id, price_per_day, start_date, end_date, no_of_days, rent, security, name, mobile_no, address, email, payment_status, booking_status));

            }
            initComponents();
            tm = new mytablemodel();
            setSize(1600,900);
            setExtendedState(MAXIMIZED_BOTH);
            setLocationRelativeTo(null);
            jt1.setModel(tm);
            tm.fireTableDataChanged();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserBookingHistory");
        getContentPane().setLayout(null);

        bt2.setBackground(new java.awt.Color(225, 179, 40));
        bt2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt2.setText("<-----");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(20, 20, 73, 27);

        bt3.setBackground(new java.awt.Color(0, 0, 0));
        bt3.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        bt3.setForeground(new java.awt.Color(223, 167, 0));
        bt3.setText("Remove booking");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(650, 650, 300, 100);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(214, 170, 37));
        jLabel1.setText("User Booking History");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 20, 560, 100);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));

        jt1.setAutoCreateRowSorter(true);
        jt1.setBackground(new java.awt.Color(0, 0, 0));
        jt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 179, 40)));
        jt1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jt1.setForeground(new java.awt.Color(225, 179, 40));
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jt1.setGridColor(new java.awt.Color(225, 179, 40));
        jt1.setPreferredSize(new java.awt.Dimension(300, 900));
        jt1.setRowHeight(40);
        jt1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jt1.setShowGrid(true);
        jScrollPane1.setViewportView(jt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 170, 1320, 470);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myuploads/user bookinghistory.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1600, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        UserHome ob = new UserHome();
        ob.setVisible(true);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        int del = jt1.getSelectedRow();
        try {
            int lo = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove this car?");
            if (lo == JOptionPane.YES_OPTION) {

//                ResultSet rs = DBLoader.executeQuery("select * from car_details ");
//                rs.absolute(del + 1);
//                rs.deleteRow();
                al.remove(del);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        tm.fireTableDataChanged();
    }//GEN-LAST:event_bt3ActionPerformed

    /**
     * @param args the command line arguments
     */
    class mytablemodel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return 14;
        }

        @Override
        public Object getValueAt(int i, int j) {
            UserBookingData a = al.get(i);
            if(j==0)
            {
                return a.booking_id;
            }
            else if(j==1)
            {
                return a.car_id;
            }
            else if(j==2)
            {
                return a.price_per_day;
            }
            else if(j==3)
            {
                return a.start_date;
            }
            else if(j==4)
            {
                return a.end_date;
            }
            else if(j==5)
            {
                return a.no_of_days;
            }
            else if(j==6)
            {
                return a.rent;
            }
            else if(j==7)
            {
                return a.security;
            }
            else if(j==8)
            {
                return a.name;
            }
            else if(j==9)
            {
                return a.mobile_no;
            }
            else if(j==10)
            {
                return a.address;
            }
            else if(j==11)
            {
                return a.email;
            }
            else if(j==12)
            {
                return a.payment_status;
            }
            else{
                return a.booking_status;
            }
        }

        public String getColumnName(int column) {
            String name[] = {"booking_id","car_id","price_per_day","start_date","end_date","no_of_days","rent","security","name","mobile_no","address","email","payment_status","booking_status"};
            return name[column];
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserBookingHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserBookingHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt1;
    // End of variables declaration//GEN-END:variables
}
