/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import vmm.DBLoader;

import javax.swing.*;
import java.sql.ResultSet;

/**
 *
 * @author hp
 */
public class UserSignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form UserSignUpPage
     */
    public UserSignUpPage() {
        initComponents();
        setSize(1600,900);
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        pf2 = new javax.swing.JPasswordField();
        pf1 = new javax.swing.JPasswordField();
        tf1 = new javax.swing.JTextField();
        bt3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserSignUp");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 75)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 167, 0));
        jLabel1.setText("User Sign Up");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 80, 350, 100);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(223, 167, 0));
        jLabel2.setText("Email : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 270, 120, 30);

        cb1.setBackground(new java.awt.Color(0, 0, 0));
        cb1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        cb1.setForeground(new java.awt.Color(223, 167, 0));
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female", "Others" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(740, 470, 300, 40);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(223, 167, 0));
        jLabel8.setText("Already have an account ? Login from here ->");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(550, 550, 280, 30);

        bt1.setBackground(new java.awt.Color(223, 167, 0));
        bt1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt1.setText("Login");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(830, 550, 180, 30);

        bt2.setBackground(new java.awt.Color(0, 0, 0));
        bt2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        bt2.setForeground(new java.awt.Color(223, 167, 0));
        bt2.setText("Sign Up");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(530, 630, 500, 110);

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(223, 167, 0));
        jLabel3.setText("Username : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 220, 150, 30);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(223, 167, 0));
        jLabel4.setText("Confirm Password : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 420, 210, 30);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(223, 167, 0));
        jLabel5.setText("Password : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(530, 370, 150, 30);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(223, 167, 0));
        jLabel6.setText("Mobile No : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 320, 150, 30);

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(223, 167, 0));
        jLabel7.setText("Gender : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 470, 150, 30);

        tf2.setBackground(new java.awt.Color(0, 0, 0));
        tf2.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        tf2.setForeground(new java.awt.Color(223, 167, 0));
        getContentPane().add(tf2);
        tf2.setBounds(740, 270, 300, 40);

        tf3.setBackground(new java.awt.Color(0, 0, 0));
        tf3.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        tf3.setForeground(new java.awt.Color(223, 167, 0));
        getContentPane().add(tf3);
        tf3.setBounds(740, 320, 300, 40);

        pf2.setBackground(new java.awt.Color(0, 0, 0));
        pf2.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        pf2.setForeground(new java.awt.Color(223, 167, 0));
        pf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf2ActionPerformed(evt);
            }
        });
        getContentPane().add(pf2);
        pf2.setBounds(740, 370, 300, 40);

        pf1.setBackground(new java.awt.Color(0, 0, 0));
        pf1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        pf1.setForeground(new java.awt.Color(223, 167, 0));
        pf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf1ActionPerformed(evt);
            }
        });
        getContentPane().add(pf1);
        pf1.setBounds(740, 420, 300, 40);

        tf1.setBackground(new java.awt.Color(0, 0, 0));
        tf1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        tf1.setForeground(new java.awt.Color(223, 167, 0));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(740, 220, 300, 40);

        bt3.setBackground(new java.awt.Color(225, 179, 40));
        bt3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bt3.setText("<-----");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(20, 20, 73, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myuploads/submission 2.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1600, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        UserLoginPage up = new UserLoginPage();
        up.setVisible(true);
    }//GEN-LAST:event_bt1ActionPerformed

    private void pf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf2ActionPerformed

    private void pf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        try{
            String username = tf1.getText().trim();
            String password = pf1.getText().trim();

            String email = tf2.getText().trim();
            String mobileno = tf3.getText().trim();
            if(username.equals("") || password.equals("") || email.equals("") || mobileno.equals("") || cb1.getSelectedItem().toString().equals("")){
                JOptionPane.showMessageDialog(null, "Please fill all the fields");
            }
            else{

            ResultSet rs = DBLoader.executeQuery("select * from user where email = '"+email+"' or mobileno = '"+mobileno+"'");
            if(rs.next()){
                JOptionPane.showMessageDialog(this,"User already exists in the system");
            }
            else
            {
            if(pf1.getText().equals(pf2.getText())){

            rs.moveToInsertRow();
            rs.updateString("username", tf1.getText());
            rs.updateString("email", tf2.getText());
            rs.updateString("mobileno", tf3.getText());
            rs.updateString("password", pf1.getText());
            rs.updateString("gender", cb1.getSelectedItem().toString());
            rs.insertRow();
            JOptionPane.showMessageDialog(null, "Account Created Successfully");
            tf1.setText("");
            tf2.setText("");
            tf3.setText("");
            pf2.setText("");
            pf1.setText("");
            cb1.setSelectedIndex(0);
            UserLoginPage up = new UserLoginPage();
            up.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "New and confirmed password doesn't match!");
            }

            }
            }


        } catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
       Welcome  ob = new Welcome();
        ob.setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField pf1;
    private javax.swing.JPasswordField pf2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    // End of variables declaration//GEN-END:variables
}
